Repository PSE-Applications/CasualConversation_iOS, pull requests merged in 2022-07, with the labels that each got.

#15 [Feature] Configurate Record 기능 구현 (재생 및 녹음 기본 기능)
  CasualConversation/Targets/CasualConversation/Sources/CasualConversationApp.swift
  CasualConversation/Targets/CasualConversation/Sources/DIContainer/AppDIContainer.swift
  CasualConversation/Targets/Data/Sources/ConversationRepository.swift
  CasualConversation/Targets/Data/Sources/LocalRepository/CoreData/CoreDataRepository.swift
  CasualConversation/Targets/Data/Sources/LocalRepository/CoreData/CoreDataRepositoryProtocol.swift
  CasualConversation/Targets/Data/Sources/LocalRepository/FileManager/FileManagerRepository.swift
  CasualConversation/Targets/Data/Sources/LocalRepository/FileManager/FileManagerRepositoryProtocol.swift
  CasualConversation/Targets/Data/Sources/NoteRepository.swift
  CasualConversation/Targets/Data/Sources/RecordRepository.swift
  CasualConversation/Targets/Domain/Sources/Interface/Repository/RecordRepositoryProtocol.swift
  CasualConversation/Targets/Domain/Sources/Model/Conversation.swift
  CasualConversation/Targets/Domain/Sources/Service/AudioService/AudioPlayer.swift
  CasualConversation/Targets/Domain/Sources/Service/AudioService/AudioRecorder.swift
  CasualConversation/Targets/Domain/Sources/Service/AudioService/AudioService.swift
  CasualConversation/Targets/Domain/Sources/Service/AudioService/AudioStatus.swift
  CasualConversation/Targets/Domain/Sources/Service/RecordService.swift
  CasualConversation/Targets/Domain/Sources/UseCase/ConversationUsecase.swift
  CasualConversation/Targets/Domain/Sources/UseCase/NoteUsecase.swift
  CasualConversation/Targets/Presentation/Sources/ConversationListView/ConversationListView.swift
  CasualConversation/Targets/Presentation/Sources/ConversationListView/ConversationListViewModel.swift
  CasualConversation/Targets/Presentation/Sources/ConversationListView/SelectionView/SelectionView.swift
  CasualConversation/Targets/Presentation/Sources/ConversationListView/SelectionView/SelectionViewModel.swift
  CasualConversation/Targets/Presentation/Sources/DIContainer/PresentationDIContainer.swift
Labels: feature, refactor

#19 [Refactor] AudioService Access Repository 구조변경
  CasualConversation/Targets/Data/Sources/LocalRepository/FileManager/FileManagerRepository.swift
  CasualConversation/Targets/Data/Sources/RecordRepository.swift
  CasualConversation/Targets/Data/Tests/DataLayerTests.swift
  CasualConversation/Targets/Data/Tests/Specs/RecorderRepositorySpecs.swift
  CasualConversation/Targets/Domain/Sources/Interface/Repository/RecordRepositoryProtocol.swift
  CasualConversation/Targets/Domain/Sources/Interface/Service/AudioPlayerProtocol.swift
  CasualConversation/Targets/Domain/Sources/Interface/Service/AudioRecorderProtocol.swift
  CasualConversation/Targets/Domain/Sources/Service/AudioService/AudioPlayer.swift
  CasualConversation/Targets/Domain/Sources/Service/AudioService/AudioRecorder.swift
  CasualConversation/Targets/Domain/Sources/Service/AudioService/AudioService.swift
  CasualConversation/Targets/Domain/Sources/Service/AudioService/AudioStatus.swift
  CasualConversation/Targets/Domain/Sources/UseCase/ConversationUsecase.swift
Labels: refactor

#20 [Test] BDD Module UnitTest - App & Presentation Layer & AudioService
  CasualConversation/Project.swift
  CasualConversation/Targets/CasualConversation/Tests/CasualConversationTests.swift
  CasualConversation/Targets/CasualConversation/Tests/Specs/DIContainer/AppDIContainerSpecs.swift
  CasualConversation/Targets/Data/Tests/DataLayerTests.swift
  CasualConversation/Targets/Data/Tests/Specs/RecordRepositorySpecs.swift
  CasualConversation/Targets/Data/Tests/Specs/RecorderRepositorySpecs.swift
  CasualConversation/Targets/Domain/Sources/Interface/Service/AudioRecorderProtocol.swift
  CasualConversation/Targets/Domain/Sources/Model/Conversation.swift
  CasualConversation/Targets/Domain/Sources/Service/AudioService/AudioService.swift
  CasualConversation/Targets/Domain/Sources/UseCase/ConversationUseCase.swift
  CasualConversation/Targets/Domain/Tests/DomainTests.swift
  CasualConversation/Targets/Domain/Tests/Specs/Mocks/MockAudioPlayer.swift
  CasualConversation/Targets/Domain/Tests/Specs/Mocks/MockAudioRecorder.swift
  CasualConversation/Targets/Domain/Tests/Specs/Mocks/MockRecordRepository.swift
  CasualConversation/Targets/Domain/Tests/Specs/Service/AudioServiceSpecs.swift
  CasualConversation/Targets/Presentation/Sources/DIContainer/PresentationDIContainer.swift
  CasualConversation/Targets/Presentation/Tests/PresentationTests.swift
  CasualConversation/Targets/Presentation/Tests/Specs/DIContainer/PresentationDIContainerSpecs.swift
  CasualConversation/Tuist/ProjectDescriptionHelpers/Extensions.swift
Labels: feature, refactor

#22 [Refactor] UnitTest BDD 형태로 리팩토링 with Quick Nimble 및 메서드 Completion 방식 변경
  CasualConversation/Targets/CasualConversation/Sources/CasualConversationApp.swift
  CasualConversation/Targets/CasualConversation/Sources/DIContainer/AppDIContainer.swift
  CasualConversation/Targets/CasualConversation/Tests/CasualConversationTests.swift
  CasualConversation/Targets/CasualConversation/Tests/Specs/AppDIContainerSpecs.swift
  CasualConversation/Targets/CasualConversation/Tests/Specs/DIContainer/AppDIContainerSpecs.swift
  CasualConversation/Targets/Data/Sources/ConversationRepository.swift
  CasualConversation/Targets/Data/Sources/LocalRepository/CoreData/CoreDataRepository.swift
  CasualConversation/Targets/Data/Sources/LocalRepository/CoreData/CoreDataRepositoryProtocol.swift
  CasualConversation/Targets/Data/Sources/LocalRepository/CoreData/Persistence.swift
  CasualConversation/Targets/Data/Sources/LocalRepository/FileManager/FileManagerRepository.swift
  CasualConversation/Targets/Data/Sources/LocalRepository/FileManager/FileManagerRepositoryProtocol.swift
  CasualConversation/Targets/Data/Sources/NoteRepository.swift
  CasualConversation/Targets/Data/Sources/RecordRepository.swift
  CasualConversation/Targets/Data/Tests/DataLayerTests.swift
  CasualConversation/Targets/Data/Tests/Specs/LocalRepository/RecordRepositorySpecs.swift
  CasualConversation/Targets/Data/Tests/Specs/RecordRepositorySpecs.swift
  CasualConversation/Targets/Domain/Sources/Interface/Repository/ConversationRepositoryProtocol.swift
  CasualConversation/Targets/Domain/Sources/Interface/Repository/NoteRepositoryProtocol.swift
  CasualConversation/Targets/Domain/Sources/Interface/Repository/RecordRepositoryProtocol.swift
  CasualConversation/Targets/Domain/Sources/Interface/Service/AudioPlayerProtocol.swift
  CasualConversation/Targets/Domain/Sources/Interface/Service/AudioRecorderProtocol.swift
  CasualConversation/Targets/Domain/Sources/Model/Conversation.swift
  CasualConversation/Targets/Domain/Sources/Model/Member.swift
  CasualConversation/Targets/Domain/Sources/Model/Note.swift
  CasualConversation/Targets/Domain/Sources/Service/AudioService/AudioService.swift
  CasualConversation/Targets/Domain/Sources/Service/AudioService/AudioStatus.swift
  CasualConversation/Targets/Domain/Sources/UseCase/ConversationUseCase.swift
  CasualConversation/Targets/Domain/Sources/UseCase/NoteUsecase.swift
  CasualConversation/Targets/Domain/Tests/DomainTests.swift
  CasualConversation/Targets/Domain/Tests/Specs/Mocks/Repository/MockRecordRepository.swift
  CasualConversation/Targets/Domain/Tests/Specs/Mocks/Service/MockAudioPlayer.swift
  CasualConversation/Targets/Domain/Tests/Specs/Mocks/Service/MockAudioRecorder.swift
  CasualConversation/Targets/Domain/Tests/Specs/Service/AudioServiceSpecs.swift
  CasualConversation/Targets/Presentation/Sources/ConversationListView/ConversationListViewModel.swift
  CasualConversation/Targets/Presentation/Sources/ConversationListView/SelectionView/SelectionViewModel.swift
  CasualConversation/Targets/Presentation/Sources/DIContainer/PresentationDIContainer.swift
  CasualConversation/Targets/Presentation/Sources/MainTabViewModel.swift
  CasualConversation/Targets/Presentation/Sources/NoteSetView/NoteSetViewModel.swift
  CasualConversation/Targets/Presentation/Sources/RecordView/RecordViewModel.swift
  CasualConversation/Targets/Presentation/Tests/PresentationTests.swift
  CasualConversation/Targets/Presentation/Tests/Specs/DIContainer/PresentationDIContainerSpecs.swift
Labels: refactor

#25 Feature cc error
  CasualConversation/.package.resolved
  CasualConversation/Targets/Common/Sources/Error/CasualConversationError.swift
Labels: feature

#29 [Refactor] Configure CCError (CC, CasualConversation)
  CasualConversation/Targets/Common/Sources/Error/CasualConversationError.swift
  CasualConversation/Targets/Data/Sources/ConversationRepository.swift
  CasualConversation/Targets/Data/Sources/NoteRepository.swift
  CasualConversation/Targets/Domain/Sources/DataLayerInterface/Repository/ConversationRepositoryProtocol.swift
  CasualConversation/Targets/Domain/Sources/DataLayerInterface/Repository/NoteRepositoryProtocol.swift
  CasualConversation/Targets/Domain/Sources/DataLayerInterface/Repository/RecordRepositoryProtocol.swift
  CasualConversation/Targets/Domain/Sources/DataLayerInterface/Service/AudioPlayerProtocol.swift
  CasualConversation/Targets/Domain/Sources/DataLayerInterface/Service/AudioRecorderProtocol.swift
  CasualConversation/Targets/Domain/Sources/Interface/Repository/ConversationRepositoryProtocol.swift
  CasualConversation/Targets/Domain/Sources/Interface/Repository/NoteRepositoryProtocol.swift
  CasualConversation/Targets/Domain/Sources/Service/AudioService/AudioService.swift
  CasualConversation/Targets/Domain/Sources/UseCase/ConversationUseCase.swift
  CasualConversation/Targets/Domain/Sources/UseCase/NoteUsecase.swift
  CasualConversation/Targets/Domain/Tests/Specs/Mocks/Repository/MockConversationRepository.swift
  CasualConversation/Targets/Domain/Tests/Specs/Mocks/Repository/MockNoteRepository.swift
  CasualConversation/Targets/Domain/Tests/Specs/Service/AudioServiceSpecs.swift
  CasualConversation/Targets/Domain/Tests/Specs/Service/ConversationUseCaseSpecs.swift
  CasualConversation/Targets/Domain/Tests/Specs/Service/NoteUseCaseSpecs.swift
  CasualConversation/Targets/Presentation/Sources/ConversationListView/ConversationListViewModel.swift
  CasualConversation/Targets/Presentation/Sources/ConversationListView/SelectionView/SelectionViewModel.swift
  CasualConversation/Targets/Presentation/Sources/DIContainer/PresentationDIContainer.swift
  CasualConversation/Targets/Presentation/Sources/NoteSetView/NoteSetViewModel.swift
  CasualConversation/Targets/Presentation/Sources/RecordView/RecordViewModel.swift
Labels: feature, refactor
